config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'

  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  content      :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  project_id   :bigint           not null
#
# Indexes
#
#  index_tasks_on_project_id  (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#
class Task < ApplicationRecord
  belongs_to :project

  def completed?
    completed_at.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[destroy complete]

  def create
    @task = @project.tasks.create(task_params)

    redirect_to @project
  end

  def destroy
    flash[:notice] = if @task.destroy
                       'Task was deleted.'
                     else
                       'Task was not deleted.'
                     end
    redirect_to @project
  end

  def complete
    @task.update(completed_at: Time.zone.now)
    redirect_to @project, notice: 'Task Completed'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice.present? || alert.present? %>
    <div aria-live="polite" aria-atomic="true" class="position-relative">
      <div class="toast-container top-0 end-0 p-3">
        <% flash.each do |type, msg| %>
          <div class="toast bg-primary" role='alert' aria-atomic="true" aria-live="assertive">
            <div class="d-flex">
              <div class="toast-body">
                <div>
                  <%= msg %>
                </div>
              </div>
              <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 class="todo_list_title">Editing Project</h1>

<div class="forms">
  <%= render 'form', project: @project %>
</div>

<div class="links">
  <%= link_to 'Cancel', projects_path %>
</div>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to project.title, project %></h2>
    <p class="todo_list_subtitle"><%= project.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to 'New Projects', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1 class="todo_list_title">New Project</h1>

<div class="forms">
  <%= render 'form', project: @project %>
</div>

<div class="links">
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<h2 class="todo_list_title"><%= @project.title %></h2>
<p class="todo_list_sub_title"><%= @project.description %></p>

<div id="todo_items_wrapper">
  <%= render @project.tasks %>
  <div id="form">
    <%= render 'tasks/form' %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %> |
  <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: [@project, @project.tasks.build] do |f| %>
  <%= f.text_field :content, placeholder: 'New Task'  %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix">
  <% if task.completed? %>
    <div class="complete">
      <%= link_to complete_project_task_path(@project, task.id), method: :patch do %>
        <div style="opacity: 0.4;" class="fas fa-check text-white"></div>
      <% end %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= task.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: 'are you sure?' } do %>
        <div class="fas fa-trash text-white"></div>
      <% end %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_project_task_path(@project, task.id), method: :patch do %>
        <div class="fas fa-check text-white"></div>
      <% end %>
    </div>
    <div class="todo_item">
      <p><%= task.content %></p>
    </div>
    <div class="trash">
      <%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: 'are you sure?' } do %>
        <div class="fas fa-trash text-white"></div>
      <% end %>
    </div>
  <% end %>
</div>